// import { Connection } from "@/types/connection";

// // The 'id' field is omitted as it's generated by the addConnection function.
// const sampleConnection: Omit<Connection, "id"> = {
//   name: "My Test Connection",
//   type: "mysql", // or "postgresql", "mongodb"
//   host: "localhost",
//   port: 3306, // or 5432 for postgres, 27017 for mongodb
//   user: "root",
//   password: "password",
//   database: "testdb",
//   encryptedCredentials: "", // This will be populated by the client-side encryption
//   filepath: "",
// };

// function generateToken(connection: Omit<Connection, "id">): string {
//   const jsonString = JSON.stringify(connection);
//   return Buffer.from(jsonString).toString("base64");
// }

// const token = generateToken(sampleConnection);
// console.log("Generated Token:");
// console.log(token);
// console.log(
//   "\nUse this token in your URL: http://localhost:3000/studio?token=" + token
// );
